services:
  db:
    image: postgres:16-alpine
    container_name: reporting_db
    environment:
      POSTGRES_DB: reporting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - reporting_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reporting"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  reporting_db_data:
